from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Any

METRICS_VERSION = "metrics/1.1"

CATEGORIES = (
    "pitch",
    "timing",
    "vowel",
    "vibrato",
    "dynamics",
    "phonation",
    "articulation",
    "breath",
    "timbre",
)
CATEGORY_LABELS = {
    "pitch": "Pitch",
    "timing": "Timing",
    "vowel": "Vowel",
    "vibrato": "Vibrato",
    "dynamics": "Dynamics",
    "phonation": "Phonation",
    "articulation": "Articulation",
    "breath": "Breath",
    "timbre": "Timbre",
}
DEFAULT_CATEGORY_WEIGHTS = {
    "pitch": 1.0,
    "timing": 0.9,
    "vowel": 0.8,
    "vibrato": 0.7,
    "dynamics": 0.6,
    "phonation": 0.6,
    "articulation": 0.5,
    "breath": 0.4,
    "timbre": 0.4,
}
CATEGORY_WEIGHT_RATIONALE = (
    "Default category weights reflect how strongly each dimension usually shapes whether an imitation is heard as "
    "'the same performance': intonation and timing first, then vowel colour and vibrato, then dynamics, phonation, "
    "articulation, breathing and overall spectral balance. They are editable and are not a validated perceptual model."
)
PRESENCE_MISMATCH_Z = 2.0


@dataclass(frozen=True)
class MetricDef:
    id: str
    category: str
    name: str
    unit: str
    tolerance: float
    weight: float
    importance: float
    trainability: float
    basis: str
    description: str
    why: str
    tolerance_basis: str
    higher: str
    lower: str
    anatomy_dependent: bool = False
    kind: str = "difference"

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


_DEFS: tuple[MetricDef, ...] = (
    MetricDef(
        "pitch.center",
        "pitch",
        "Note centre",
        "cents",
        15.0,
        1.0,
        1.0,
        0.9,
        "measured",
        "Mean pitch of the note's stable core compared with the reference note (after removing any whole-semitone transposition).",
        "Sustained mistuning is the most readily noticed pitch error.",
        "Listeners typically notice sustained-note mistuning of roughly 10-25 cents in a musical context.",
        "sharp",
        "flat",
    ),
    MetricDef(
        "pitch.scoop",
        "pitch",
        "Scoop into the note",
        "cents",
        50.0,
        0.7,
        0.65,
        0.85,
        "measured",
        "How far below (or above) the target the note starts before settling, compared with the reference.",
        "Scoops and direct attacks are signature stylistic choices that shape a singer's sound.",
        "Approach offsets under ~50 cents over a short attack are hard to hear.",
        "more scooped",
        "more direct",
    ),
    MetricDef(
        "pitch.attack_time",
        "pitch",
        "Time to reach pitch",
        "ms",
        60.0,
        0.5,
        0.5,
        0.85,
        "measured",
        "Time from the note onset until the pitch settles within 25 cents of its centre.",
        "Slow or fast settling changes how 'sung-in' or 'placed' a note sounds.",
        "Attack-time differences below ~60 ms are rarely noticed.",
        "slower to settle",
        "faster to settle",
    ),
    MetricDef(
        "pitch.overshoot",
        "pitch",
        "Overshoot",
        "cents",
        30.0,
        0.5,
        0.45,
        0.8,
        "derived",
        "Excursion past the note centre right after the attack.",
        "Overshooting ascending intervals is a common habit that sounds effortful.",
        "Brief excursions below ~30 cents are masked by the attack.",
        "more overshoot",
        "less overshoot",
    ),
    MetricDef(
        "pitch.drift",
        "pitch",
        "Pitch drift",
        "cents/s",
        25.0,
        0.4,
        0.4,
        0.8,
        "derived",
        "Slope of the vibrato-free pitch trend across the note's core.",
        "Sagging or creeping pitch on long notes is audible even when the average is right.",
        "Drifts below ~25 cents per second rarely accumulate to an audible error.",
        "rising more",
        "sagging more",
    ),
    MetricDef(
        "pitch.stability",
        "pitch",
        "Pitch steadiness",
        "cents",
        8.0,
        0.35,
        0.35,
        0.6,
        "derived",
        "Standard deviation of the slow (non-vibrato) pitch trend over the note core.",
        "Unsteady pitch reads as uncertainty or wobble.",
        "Slow wander below ~8 cents is within normal steadiness.",
        "less steady",
        "steadier",
    ),
    MetricDef(
        "pitch.release",
        "pitch",
        "Note release",
        "cents",
        60.0,
        0.35,
        0.35,
        0.8,
        "measured",
        "Pitch at the end of the note relative to its centre (falls or lifts at the release).",
        "Fall-offs and lifts at note endings are stylistic signatures.",
        "Release offsets below ~60 cents are brief and usually masked.",
        "lifting more",
        "falling more",
    ),
    MetricDef(
        "pitch.transition",
        "pitch",
        "Legato transition",
        "ms",
        60.0,
        0.45,
        0.5,
        0.75,
        "derived",
        "Duration of the pitch glide between connected notes.",
        "Portamento speed defines how smooth or crisp a melodic line sounds.",
        "Glide-duration differences under ~60 ms are hard to hear.",
        "slower glide",
        "faster glide",
    ),
    MetricDef(
        "timing.phrase_onset",
        "timing",
        "Phrase entry",
        "ms",
        60.0,
        1.0,
        0.9,
        1.0,
        "derived",
        "When the first note of the phrase starts, relative to where the reference timing predicts it (after removing overall tempo and offset).",
        "Early or late entries are among the most noticeable rhythmic differences.",
        "Onset asynchronies above roughly 30-60 ms become audible in singing.",
        "late",
        "early",
    ),
    MetricDef(
        "timing.note_onset",
        "timing",
        "Note timing within the phrase",
        "ms",
        50.0,
        0.8,
        0.7,
        0.95,
        "derived",
        "Note onset relative to the phrase's own start, compared with the reference rhythm.",
        "Rhythmic placement inside the phrase (anticipation, laid-back feel) defines phrasing.",
        "Onset differences under ~50 ms are within normal expressive variation.",
        "late",
        "early",
    ),
    MetricDef(
        "timing.duration",
        "timing",
        "Note length",
        "%",
        15.0,
        0.6,
        0.6,
        0.95,
        "derived",
        "Note duration relative to the reference after accounting for overall tempo.",
        "Held-note lengths shape phrasing and breath placement.",
        "Duration differences under ~15% are rarely noticed.",
        "longer",
        "shorter",
    ),
    MetricDef(
        "timing.hold",
        "timing",
        "Final hold",
        "ms",
        120.0,
        0.7,
        0.6,
        1.0,
        "derived",
        "How long the last note of a phrase is held compared with the reference (tempo-adjusted).",
        "Phrase-final holds are conspicuous because nothing masks them.",
        "Differences under ~120 ms at phrase ends are rarely noticed.",
        "held longer",
        "cut shorter",
    ),
    MetricDef(
        "vibrato.presence",
        "vibrato",
        "Vibrato on/off",
        "",
        1.0,
        0.9,
        0.8,
        0.8,
        "measured",
        "Whether the note has vibrato where the reference does (or not).",
        "Using straight tone versus vibrato is one of the clearest stylistic contrasts.",
        "A presence mismatch is always audible on sustained notes.",
        "added vibrato",
        "missing vibrato",
        kind="presence",
    ),
    MetricDef(
        "vibrato.rate",
        "vibrato",
        "Vibrato rate",
        "Hz",
        0.35,
        1.0,
        0.8,
        0.6,
        "measured",
        "Oscillations per second on notes where both performances use vibrato.",
        "Vibrato rate is highly characteristic of a singer; fast rates sound nervous, slow rates wobbly.",
        "Rate differences of ~0.3-0.5 Hz are reported as noticeable in listening studies.",
        "faster",
        "slower",
    ),
    MetricDef(
        "vibrato.extent",
        "vibrato",
        "Vibrato width",
        "cents (±)",
        12.0,
        0.9,
        0.7,
        0.7,
        "measured",
        "Half the peak-to-trough pitch excursion of the vibrato.",
        "Width controls how prominent and 'operatic' versus subtle the vibrato sounds.",
        "Width differences below ~12 cents (±) are subtle.",
        "wider",
        "narrower",
    ),
    MetricDef(
        "vibrato.onset",
        "vibrato",
        "Vibrato onset",
        "ms",
        120.0,
        0.8,
        0.65,
        0.85,
        "measured",
        "How long the note stays straight before the vibrato starts.",
        "Delayed vibrato is a hallmark of many pop and jazz singers.",
        "Onset timing differences under ~120 ms are hard to hear.",
        "starts later",
        "starts earlier",
    ),
    MetricDef(
        "vibrato.regularity",
        "vibrato",
        "Vibrato evenness",
        "",
        0.15,
        0.3,
        0.3,
        0.5,
        "derived",
        "Consistency of cycle length and width (1 = perfectly even).",
        "Uneven vibrato sounds unsettled.",
        "Regularity differences under 0.15 are subtle.",
        "more even",
        "less even",
    ),
    MetricDef(
        "vowel.f1",
        "vowel",
        "Vowel openness (F1)",
        "%",
        8.0,
        1.0,
        0.8,
        0.8,
        "derived",
        "First formant relative to the reference on the same syllable, after removing the overall vocal-tract scaling between the two voices.",
        "F1 tracks how open the vowel sounds; openness changes vowel identity and brightness.",
        "Formant changes of roughly 5-10% are near the discrimination threshold for vowels.",
        "more open",
        "more closed",
    ),
    MetricDef(
        "vowel.f2",
        "vowel",
        "Vowel frontness (F2)",
        "%",
        8.0,
        1.0,
        0.8,
        0.8,
        "derived",
        "Second formant relative to the reference on the same syllable, after vocal-tract normalisation.",
        "F2 tracks front/back quality; it is a major cue for vowel colour.",
        "Formant changes of roughly 5-10% are near the discrimination threshold for vowels.",
        "more fronted",
        "more backed",
    ),
    MetricDef(
        "vowel.movement",
        "vowel",
        "Vowel movement",
        "log units",
        0.1,
        0.5,
        0.5,
        0.75,
        "derived",
        "How much the vowel moves from start to end (diphthong glide size).",
        "Diphthong timing and size are strong accent and style markers.",
        "Movement differences under 0.1 log units (~10%) are subtle.",
        "moves more",
        "moves less",
    ),
    MetricDef(
        "dynamics.contour",
        "dynamics",
        "Phrase loudness shape",
        "1 - r",
        0.3,
        1.0,
        0.6,
        0.9,
        "derived",
        "Mismatch between the aligned loudness envelopes of the phrase (1 minus their correlation).",
        "The shape of loudness through a phrase carries much of its expression.",
        "Envelope correlations above ~0.7 sound similar in shape.",
        "different shape",
        "similar shape",
    ),
    MetricDef(
        "dynamics.phrase_level",
        "dynamics",
        "Phrase loudness",
        "dB",
        2.5,
        0.6,
        0.5,
        0.9,
        "measured",
        "Phrase loudness relative to each performance's own typical singing level.",
        "Relative loudness between phrases builds the arc of a song.",
        "Level differences under ~2.5 dB are near the loudness discrimination threshold for music.",
        "louder",
        "softer",
    ),
    MetricDef(
        "dynamics.note_change",
        "dynamics",
        "Crescendo / decrescendo",
        "dB",
        2.5,
        0.8,
        0.55,
        0.9,
        "measured",
        "Loudness change from the first to the last third of the note.",
        "Swells and fades on held notes are highly expressive.",
        "Changes under ~2.5 dB are subtle.",
        "grows more",
        "fades more",
    ),
    MetricDef(
        "dynamics.emphasis",
        "dynamics",
        "Note emphasis",
        "dB",
        2.5,
        0.5,
        0.4,
        0.85,
        "derived",
        "Note loudness relative to its phrase.",
        "Stress patterns shape the lyric's meaning and groove.",
        "Emphasis differences under ~2.5 dB are subtle.",
        "more stressed",
        "less stressed",
    ),
    MetricDef(
        "dynamics.attack",
        "dynamics",
        "Attack strength",
        "dB",
        4.0,
        0.4,
        0.35,
        0.85,
        "measured",
        "Loudness rise over the first 120 ms of the note.",
        "Attack strength changes how punchy or soft entries feel.",
        "Rise differences under ~4 dB are subtle.",
        "punchier",
        "softer",
    ),
    MetricDef(
        "phonation.breathiness",
        "phonation",
        "Breathiness",
        "0-100",
        12.0,
        1.0,
        0.7,
        0.6,
        "derived",
        "CPPS-based breathiness index (0 = clear, 100 = very breathy) on the same note.",
        "Airy versus clear tone is one of the most recognisable aspects of a voice's colour.",
        "A 12-point change corresponds to ~1.7 dB CPPS, around the smallest difference listeners reliably report.",
        "breathier",
        "clearer",
    ),
    MetricDef(
        "phonation.h1h2",
        "phonation",
        "Spectral tilt at the source (H1-H2)",
        "dB",
        4.0,
        0.5,
        0.5,
        0.55,
        "measured",
        "Difference between the first two harmonics on the same syllable.",
        "Higher H1-H2 usually sounds lighter or breathier; lower values sound more pressed.",
        "Differences under ~4 dB are within normal variation.",
        "lighter / more open",
        "heavier / more pressed",
    ),
    MetricDef(
        "phonation.hnr",
        "phonation",
        "Harmonics-to-noise ratio",
        "dB",
        4.0,
        0.3,
        0.45,
        0.6,
        "measured",
        "Harmonic energy relative to noise on the same note.",
        "Lower HNR adds audible noise, hoarseness or air.",
        "Differences under ~4 dB are subtle.",
        "cleaner",
        "noisier",
    ),
    MetricDef(
        "phonation.cpps",
        "phonation",
        "Cepstral peak prominence",
        "dB",
        2.0,
        0.0,
        0.45,
        0.6,
        "measured",
        "Smoothed CPP on the same note (shown as evidence; already scored through breathiness).",
        "CPPS is the most robust single acoustic correlate of breathiness.",
        "Differences under ~2 dB are subtle.",
        "clearer",
        "breathier",
    ),
    MetricDef(
        "articulation.consonant_duration",
        "articulation",
        "Consonant length",
        "ms",
        35.0,
        1.0,
        0.5,
        0.9,
        "measured",
        "Duration of the matched consonant.",
        "Consonant length changes diction, rhythm and the crispness of text.",
        "Consonant duration differences under ~35 ms are rarely noticed.",
        "longer",
        "shorter",
    ),
    MetricDef(
        "articulation.cv_ratio",
        "articulation",
        "Consonant strength",
        "dB",
        4.0,
        0.6,
        0.4,
        0.85,
        "measured",
        "Consonant loudness relative to the neighbouring vowel.",
        "Consonant energy decides how crisp or soft the diction sounds.",
        "Differences under ~4 dB are subtle.",
        "stronger",
        "softer",
    ),
    MetricDef(
        "articulation.missing_consonant",
        "articulation",
        "Missing consonant",
        "",
        1.0,
        0.8,
        0.6,
        0.9,
        "derived",
        "A consonant clearly present in the reference that could not be found at the aligned position in the take.",
        "Dropped consonants blur the words.",
        "Always audible when the reference consonant is clear.",
        "extra",
        "missing",
        kind="presence",
    ),
    MetricDef(
        "articulation.onset_type",
        "articulation",
        "Vowel onset style",
        "",
        1.0,
        0.5,
        0.4,
        0.8,
        "derived",
        "Hard (glottal), balanced or breathy start of the phrase's first vowel.",
        "Onset style changes the character of every phrase entry.",
        "Category changes are audible when the evidence is clear.",
        "different",
        "different",
        kind="label",
    ),
    MetricDef(
        "breath.presence",
        "breath",
        "Breath placement",
        "",
        1.0,
        1.0,
        0.5,
        0.95,
        "derived",
        "Whether a breath is taken before the phrase where the reference breathes.",
        "Breath placement shapes phrasing and can break lines.",
        "Missing or extra breaths are audible when the inhale is audible.",
        "extra breath",
        "missing breath",
        kind="presence",
    ),
    MetricDef(
        "breath.duration",
        "breath",
        "Inhale length",
        "ms",
        150.0,
        0.4,
        0.2,
        0.9,
        "measured",
        "Duration of the inhale before the phrase.",
        "Longer inhales change the timing of the pickup.",
        "Differences under ~150 ms are rarely noticed.",
        "longer",
        "shorter",
    ),
    MetricDef(
        "breath.level",
        "breath",
        "Inhale loudness",
        "dB",
        6.0,
        0.5,
        0.3,
        0.85,
        "measured",
        "Loudness of the inhale relative to the singing level.",
        "Audible breaths are a deliberate stylistic element for some singers.",
        "Breath level differences under ~6 dB are subtle.",
        "louder breath",
        "quieter breath",
    ),
    MetricDef(
        "breath.phrase_end",
        "breath",
        "Phrase-end air",
        "dB",
        2.5,
        0.5,
        0.35,
        0.7,
        "derived",
        "Change in CPPS over the last 300 ms of the phrase (negative means breathier endings).",
        "Letting air into phrase endings is a stylistic signature.",
        "Changes under ~2.5 dB are subtle.",
        "clearer endings",
        "airier endings",
    ),
    MetricDef(
        "timbre.band_balance",
        "timbre",
        "Spectral balance",
        "dB",
        4.0,
        1.0,
        0.45,
        0.4,
        "measured",
        "Largest difference in the level-normalised energy share of seven broad frequency bands.",
        "Spectral balance is heard as brightness, warmth or 'ring'.",
        "Band-level differences under ~4 dB are subtle; microphones and rooms also cause differences of this size.",
        "more energy in a band",
        "less energy in a band",
        anatomy_dependent=True,
    ),
    MetricDef(
        "timbre.centroid",
        "timbre",
        "Brightness (spectral centroid)",
        "%",
        15.0,
        0.6,
        0.4,
        0.45,
        "measured",
        "Spectral centroid relative to the reference.",
        "The centroid is the strongest single correlate of perceived brightness.",
        "Centroid changes under ~15% are subtle.",
        "brighter",
        "darker",
        anatomy_dependent=True,
    ),
    MetricDef(
        "timbre.spr",
        "timbre",
        "Ring (singing power ratio)",
        "dB",
        4.0,
        0.6,
        0.45,
        0.5,
        "measured",
        "Strongest 2-4 kHz peak relative to the strongest 0-2 kHz peak.",
        "Energy around 2-4 kHz is heard as 'ring' or projection.",
        "Differences under ~4 dB are subtle.",
        "more ring",
        "less ring",
        anatomy_dependent=True,
    ),
)

METRICS: dict[str, MetricDef] = {m.id: m for m in _DEFS}


def metric(metric_id: str) -> MetricDef:
    return METRICS[metric_id]


def metrics_by_category() -> dict[str, list[MetricDef]]:
    out: dict[str, list[MetricDef]] = {c: [] for c in CATEGORIES}
    for definition in _DEFS:
        out[definition.category].append(definition)
    return out
