from __future__ import annotations

from dataclasses import dataclass

LAYERS = (
    "waveform",
    "pitch",
    "vibrato",
    "formants",
    "spectrogram",
    "loudness",
    "phonetic",
    "breath",
    "confidence",
    "vowel_space",
)


@dataclass(frozen=True)
class Guidance:
    title: str
    beginner: str
    expert: str
    adjust: str
    exercise: str
    layers: tuple[str, ...]
    adjust_basis: str = "stylistic"


def _g(
    title: str,
    beginner: str,
    expert: str,
    adjust: str,
    exercise: str,
    layers: tuple[str, ...],
    basis: str = "stylistic",
) -> Guidance:
    return Guidance(title, beginner, expert, adjust, exercise, layers, basis)


GUIDANCE: dict[tuple[str, str], Guidance] = {
    ("pitch.center", "flat"): _g(
        "Notes land flat",
        "You're singing slightly under the note {where}. Aim a little higher and listen for the note to lock in with the reference.",
        "Median centre deviation {diff} (n={n}, after {transposition}); worst {worst}.",
        "Pre-hear the target before you sing it and keep airflow steady to the end of the note; flatness on held notes often comes from letting support drop.",
        "Loop the phrase at 80% speed. Hum the target on 'ng' against the reference until it beats-free, then open to the vowel without letting the pitch fall.",
        ("pitch",),
    ),
    ("pitch.center", "sharp"): _g(
        "Notes land sharp",
        "You're singing slightly above the note {where}. Aim a little lower and relax into the pitch.",
        "Median centre deviation {diff} (n={n}, after {transposition}); worst {worst}.",
        "Sharpness on high or loud notes often comes from pushing; try the same note a little softer and let it settle down onto the target.",
        "Loop the note. Sing it at half volume against the reference until the pitch matches, then restore the volume without letting it climb.",
        ("pitch",),
    ),
    ("pitch.scoop", "more direct"): _g(
        "Reference scoops in; you attack directly",
        "The singer slides up into {where}; you start right on the note. Try starting a little lower and sliding up.",
        "Reference approach {ref} below the centre; yours {user} (n={n}).",
        "Start about {ref_abs} below the target and glide up over the first ~{ref_attack} of the note, the way the reference 'leans into' it.",
        "Loop the note. Sing a slow glide from a semitone below into the target, then shorten the glide until it matches the reference.",
        ("pitch",),
    ),
    ("pitch.scoop", "more scooped"): _g(
        "You scoop into notes the reference hits directly",
        "You slide up into {where}; the singer starts right on the note. Try to land on the pitch from the start.",
        "Your approach starts {user} from the centre versus {ref} for the reference (n={n}).",
        "Pre-hear the pitch and start the vowel on it. A brief hum or a soft 'h' onset on the target pitch helps you find it before the vowel.",
        "Loop the note. Sing it staccato ('hah') on pitch three times, then sustain it with the same clean start.",
        ("pitch",),
    ),
    ("pitch.attack_time", "slower to settle"): _g(
        "Notes take longer to settle",
        "Your pitch takes longer to arrive {where}.",
        "Time to reach ±25 cents: {user} vs {ref} (median difference {diff}, n={n}).",
        "Aim for the centre of the note earlier; think of arriving on the vowel rather than tuning into it.",
        "Loop the entry and sing only the first half-second, landing on pitch as fast as the reference does.",
        ("pitch",),
    ),
    ("pitch.attack_time", "faster to settle"): _g(
        "You settle on notes faster than the reference",
        "The singer eases into {where} more gradually than you do.",
        "Time to reach ±25 cents: {user} vs {ref} (median difference {diff}, n={n}).",
        "Allow a slightly longer, relaxed approach into the note, as the reference does.",
        "Loop the entry and match the reference's settling time by ear before recording again.",
        ("pitch",),
    ),
    ("pitch.overshoot", "more overshoot"): _g(
        "You overshoot notes after the attack",
        "You go past the note and come back {where}.",
        "Overshoot {user} vs {ref} (n={n}).",
        "Overshooting usually comes from reaching with too much effort; aim for the centre and let the interval land softly.",
        "Loop the interval slowly on a glide, stopping exactly on the target without passing it.",
        ("pitch",),
    ),
    ("pitch.overshoot", "less overshoot"): _g(
        "The reference overshoots and bounces back",
        "The singer slightly passes the note and returns {where}; you land straight on it.",
        "Reference overshoot {ref}; yours {user} (n={n}).",
        "If you want this stylistic 'spring', let the pitch flick just past the target and fall back into it.",
        "Loop the note and imitate the flick at a slow tempo first.",
        ("pitch",),
    ),
    ("pitch.drift", "sagging more"): _g(
        "Pitch sags during held notes",
        "Your pitch slowly drops while you hold {where}.",
        "Drift {user} vs {ref} (n={n}).",
        "Sagging on sustained notes often means airflow or support is fading; keep a steady, slightly increasing breath pressure to the end.",
        "Hold the note for its full length against the reference drone, listening for the moment the pitch starts to drop.",
        ("pitch",),
    ),
    ("pitch.drift", "rising more"): _g(
        "Pitch creeps upward on held notes",
        "Your pitch slowly rises while you hold {where}.",
        "Drift {user} vs {ref} (n={n}).",
        "Rising pitch on held notes often comes from increasing tension or pressure; keep the throat relaxed as you sustain.",
        "Hold the note at a softer dynamic and listen for the pitch staying put.",
        ("pitch",),
    ),
    ("pitch.stability", "less steady"): _g(
        "Pitch wanders on held notes",
        "Your pitch wobbles slowly (not vibrato) {where}.",
        "Slow pitch deviation {user} vs {ref} (n={n}).",
        "Slow wander usually means the note isn't anchored yet; practise holding it with a steady breath before adding style.",
        "Sustain the note on a straight tone for 4 seconds with the reference playing, then reintroduce the vibrato.",
        ("pitch",),
    ),
    ("pitch.stability", "steadier"): _g(
        "The reference lets pitch move more freely",
        "The singer's held notes drift more than yours {where}.",
        "Slow pitch deviation {user} vs {ref} (n={n}).",
        "This is stylistic looseness; only copy it if you want the same relaxed feel.",
        "Listen to the reference note in slow playback and imitate its gentle movement.",
        ("pitch",),
    ),
    ("pitch.release", "falling more"): _g(
        "Your notes fall off at the end",
        "Your pitch drops at the end of {where} more than the singer's.",
        "Release offset {user} vs {ref} (n={n}).",
        "Keep the pitch and breath steady through the release, then stop the note cleanly instead of letting it fall.",
        "Sing the note and end it with a clean release on pitch, like placing it down.",
        ("pitch",),
    ),
    ("pitch.release", "lifting more"): _g(
        "Reference falls off; you hold pitch",
        "The singer lets {where} fall away at the end; you keep the pitch.",
        "Release offset {user} vs {ref} (n={n}).",
        "Let the pitch drop gently as the note ends, releasing breath and pitch together.",
        "Imitate the fall-off slowly: release the note downward over about a fifth of a second.",
        ("pitch",),
    ),
    ("pitch.transition", "slower glide"): _g(
        "Your note-to-note glides are slower",
        "You slide between notes more slowly than the singer {where}.",
        "Glide duration {user} vs {ref} (n={n}).",
        "Move to the next pitch a little later and quicker.",
        "Loop the two-note transition at 75% speed and match the glide length by ear.",
        ("pitch",),
    ),
    ("pitch.transition", "faster glide"): _g(
        "The reference glides more slowly between notes",
        "The singer slides between notes more than you do {where}.",
        "Glide duration {user} vs {ref} (n={n}).",
        "Allow a smoother, slower portamento into the next note.",
        "Loop the transition and exaggerate the glide first, then refine it.",
        ("pitch",),
    ),
    ("timing.phrase_onset", "late"): _g(
        "Late phrase entry",
        "You come in late {where}.",
        "Entry {diff} relative to the reference timing model (n={n}).",
        "Breathe earlier so the first consonant is ready before the beat, and aim to have the vowel land on the beat.",
        "Loop from the previous phrase end into this entry and clap or tap the entry point before singing it.",
        ("waveform", "loudness", "breath"),
    ),
    ("timing.phrase_onset", "early"): _g(
        "Early phrase entry",
        "You come in early {where}.",
        "Entry {diff} relative to the reference timing model (n={n}).",
        "Wait for the reference's pickup; hold the breath a moment longer before starting the phrase.",
        "Loop the entry and count the rest out loud before singing.",
        ("waveform", "loudness", "breath"),
    ),
    ("timing.note_onset", "late"): _g(
        "Notes arrive late within the phrase",
        "Some notes come later than the singer's rhythm {where}.",
        "Onset deviation {diff} within phrase (n={n}).",
        "Move to the next syllable earlier; start its consonant before the beat so the vowel lands on time.",
        "Speak the lyric in rhythm with the reference, then sing it.",
        ("waveform", "phonetic"),
    ),
    ("timing.note_onset", "early"): _g(
        "Notes arrive early within the phrase",
        "Some notes come earlier than the singer's rhythm {where}.",
        "Onset deviation {diff} within phrase (n={n}).",
        "Hold the preceding vowel a little longer before moving on.",
        "Speak the lyric in rhythm with the reference, then sing it.",
        ("waveform", "phonetic"),
    ),
    ("timing.duration", "longer"): _g(
        "Notes held longer than the reference",
        "You hold some notes longer than the singer {where}.",
        "Duration {diff} after tempo adjustment (n={n}).",
        "Move on sooner; plan where the next syllable starts.",
        "Loop the phrase and mark each note's end with a light tap.",
        ("waveform",),
    ),
    ("timing.duration", "shorter"): _g(
        "Notes cut shorter than the reference",
        "You leave some notes sooner than the singer {where}.",
        "Duration {diff} after tempo adjustment (n={n}).",
        "Sustain the vowel longer before moving to the next consonant.",
        "Loop the phrase and hold each vowel until the reference moves on.",
        ("waveform",),
    ),
    ("timing.hold", "held longer"): _g(
        "Final notes held too long",
        "You hold the last note of the phrase longer than the singer {where}.",
        "Final hold {diff} after tempo adjustment (n={n}).",
        "Release the phrase-final note together with the reference.",
        "Loop the phrase ending and release exactly when the reference stops.",
        ("waveform", "loudness"),
    ),
    ("timing.hold", "cut shorter"): _g(
        "Final notes cut short",
        "You end the last note of the phrase sooner than the singer {where}.",
        "Final hold {diff} after tempo adjustment (n={n}).",
        "Plan the breath so you can sustain to the reference's release point.",
        "Loop the phrase ending and sustain until the reference stops.",
        ("waveform", "loudness"),
    ),
    ("vibrato.presence", "missing vibrato"): _g(
        "Vibrato missing",
        "The singer uses vibrato {where}; you sing it straight.",
        "Reference vibrato present, take straight (n={n}).",
        "Let the note release into vibrato after the straight beginning; vibrato appears when the voice is free, so avoid holding the throat still.",
        "On the held note, alternate 2 s straight tone with 2 s of relaxed pulsing, then match the reference's onset.",
        ("pitch", "vibrato"),
    ),
    ("vibrato.presence", "added vibrato"): _g(
        "Vibrato where the reference is straight",
        "You add vibrato {where} where the singer keeps a straight tone.",
        "Reference straight, take with vibrato (n={n}).",
        "Hold these notes on a straight tone; keep the breath steady and avoid pulsing.",
        "Sustain the note straight for its full length against the reference.",
        ("pitch", "vibrato"),
    ),
    ("vibrato.rate", "faster"): _g(
        "Vibrato is faster",
        "Your vibrato wobbles faster than the singer's {where}.",
        "Rate {user} vs {ref} (median difference {diff}, n={n}).",
        "Fast vibrato often comes with extra tension; let the oscillation slow and widen slightly. Target about {ref}.",
        "Set a metronome to {bpm} BPM and pulse four vibrato cycles per click on a sustained vowel.",
        ("pitch", "vibrato"),
    ),
    ("vibrato.rate", "slower"): _g(
        "Vibrato is slower",
        "Your vibrato wobbles more slowly than the singer's {where}.",
        "Rate {user} vs {ref} (median difference {diff}, n={n}).",
        "Aim for a quicker, lighter oscillation (about {ref}); slow vibrato is often too wide and heavy.",
        "Set a metronome to {bpm} BPM and pulse four vibrato cycles per click on a sustained vowel.",
        ("pitch", "vibrato"),
    ),
    ("vibrato.extent", "wider"): _g(
        "Vibrato is wider",
        "Your vibrato swings further in pitch than the singer's {where}.",
        "Extent {user} vs {ref} (n={n}).",
        "Narrow the pitch swing while keeping the same speed; think 'shimmer' rather than 'wobble'.",
        "Sustain a note and gradually narrow the vibrato to about {ref}, checking the pitch lane.",
        ("pitch", "vibrato"),
    ),
    ("vibrato.extent", "narrower"): _g(
        "Vibrato is narrower",
        "Your vibrato is shallower than the singer's {where}.",
        "Extent {user} vs {ref} (n={n}).",
        "Let the pitch swing a little further on each cycle while keeping the speed.",
        "Sustain a note and gradually widen the vibrato to about {ref}, checking the pitch lane.",
        ("pitch", "vibrato"),
    ),
    ("vibrato.onset", "starts earlier"): _g(
        "Vibrato starts too early",
        "You start the vibrato sooner than the singer {where}.",
        "Straight tone before vibrato: {user} vs {ref} (median difference {diff}, n={n}).",
        "Hold the start of the note straight for about {ref} before letting the vibrato in.",
        "Loop the note. Count 'one-and' on a straight tone before releasing into vibrato.",
        ("pitch", "vibrato"),
    ),
    ("vibrato.onset", "starts later"): _g(
        "Vibrato starts too late",
        "You hold the note straight longer than the singer before adding vibrato {where}.",
        "Straight tone before vibrato: {user} vs {ref} (median difference {diff}, n={n}).",
        "Release into vibrato after about {ref}.",
        "Loop the note and release into vibrato at the reference's moment.",
        ("pitch", "vibrato"),
    ),
    ("vibrato.regularity", "less even"): _g(
        "Vibrato is uneven",
        "Your vibrato cycles vary more than the singer's {where}.",
        "Regularity {user} vs {ref} (n={n}).",
        "Even vibrato comes from steady airflow; keep the breath constant while you sustain.",
        "Sustain a note with vibrato for 5 s and aim for identical cycles.",
        ("pitch", "vibrato"),
    ),
    ("vibrato.regularity", "more even"): _g(
        "The reference vibrato is freer",
        "The singer's vibrato varies more than yours {where}.",
        "Regularity {user} vs {ref} (n={n}).",
        "This is a stylistic difference; no action needed unless you want a looser feel.",
        "Listen in slow playback and imitate the irregular cycles.",
        ("pitch", "vibrato"),
    ),
    ("vowel.f2", "more fronted"): _g(
        "Vowel is more fronted",
        "Your vowel sounds brighter and further forward than the singer's {where}.",
        "Normalised F2 {diff} (n={n}); vocal-tract scaling removed.",
        "This usually means the tongue body sits further forward. Try a slightly darker, rounder version of the vowel: move the tongue back a little or round the lips slightly.",
        "Loop the word slowly. Alternate your version and a rounder version on one pitch, and keep the one closer to the reference on the vowel chart.",
        ("formants", "vowel_space"),
        "inferred",
    ),
    ("vowel.f2", "more backed"): _g(
        "Vowel is more backed",
        "Your vowel sounds darker and further back than the singer's {where}.",
        "Normalised F2 {diff} (n={n}); vocal-tract scaling removed.",
        "This usually means the tongue sits further back or the lips are more rounded. Try bringing the tongue slightly forward or spreading the lips a little.",
        "Loop the word slowly and brighten the vowel in small steps, watching the vowel chart.",
        ("formants", "vowel_space"),
        "inferred",
    ),
    ("vowel.f1", "more open"): _g(
        "Vowel is more open",
        "Your vowel is more open than the singer's {where}.",
        "Normalised F1 {diff} (n={n}); vocal-tract scaling removed.",
        "A higher F1 usually means a lower jaw or lower tongue. Try closing the jaw slightly on this vowel.",
        "Loop the word and sing it with a slightly smaller mouth opening, checking the vowel chart.",
        ("formants", "vowel_space"),
        "inferred",
    ),
    ("vowel.f1", "more closed"): _g(
        "Vowel is more closed",
        "Your vowel is more closed than the singer's {where}.",
        "Normalised F1 {diff} (n={n}); vocal-tract scaling removed.",
        "A lower F1 usually means a higher jaw or tongue. Try dropping the jaw a little more on this vowel.",
        "Loop the word and sing it with a slightly taller mouth opening, checking the vowel chart.",
        ("formants", "vowel_space"),
        "inferred",
    ),
    ("vowel.movement", "moves more"): _g(
        "Vowel moves more than the reference",
        "Your vowel changes shape during the note more than the singer's {where}.",
        "Start-to-end movement {user} vs {ref} (n={n}).",
        "Hold the main vowel longer and delay the glide to the second vowel sound until the very end.",
        "Loop the word and sustain the first vowel sound, adding the glide only at the release.",
        ("formants", "vowel_space"),
        "inferred",
    ),
    ("vowel.movement", "moves less"): _g(
        "Vowel moves less than the reference",
        "The singer's vowel glides more during the note {where}.",
        "Start-to-end movement {user} vs {ref} (n={n}).",
        "Let the vowel glide toward its second sound, as in the reference.",
        "Loop the word slowly and exaggerate the vowel glide, then scale it back.",
        ("formants", "vowel_space"),
        "inferred",
    ),
    ("dynamics.contour", "different shape"): _g(
        "Phrase loudness shape differs",
        "The way your volume rises and falls through {where} differs from the singer's.",
        "Envelope correlation {user} (1 = identical shape; n={n}).",
        "Follow the reference's loudness arc: note where it grows and where it fades, and shape your breath to match.",
        "Loop the phrase with the loudness lane visible and trace the reference envelope with your voice.",
        ("loudness",),
    ),
    ("dynamics.phrase_level", "louder"): _g(
        "Phrase is louder relative to the rest",
        "You sing {where} louder, relative to the rest of your take, than the singer does.",
        "Phrase level {diff} relative to each performance's own typical level (n={n}).",
        "Bring this phrase down in the overall arc of the song.",
        "Sing the section at three dynamic levels and pick the one that matches the reference balance.",
        ("loudness",),
    ),
    ("dynamics.phrase_level", "softer"): _g(
        "Phrase is softer relative to the rest",
        "You sing {where} softer, relative to the rest of your take, than the singer does.",
        "Phrase level {diff} relative to each performance's own typical level (n={n}).",
        "Give this phrase more energy relative to its neighbours.",
        "Sing the section at three dynamic levels and pick the one that matches the reference balance.",
        ("loudness",),
    ),
    ("dynamics.note_change", "fades more"): _g(
        "Missing swell on held notes",
        "The singer grows louder through {where}; your note stays flat or fades.",
        "Loudness change across the note {user} vs {ref} (n={n}).",
        "Add a gradual crescendo by increasing breath energy through the note, not by pushing the throat.",
        "Sustain the note while counting to four, growing from mezzo-piano to mezzo-forte.",
        ("loudness",),
    ),
    ("dynamics.note_change", "grows more"): _g(
        "Held notes swell more than the reference",
        "You grow louder through {where} more than the singer.",
        "Loudness change across the note {user} vs {ref} (n={n}).",
        "Keep the dynamic steadier or let it relax as the reference does.",
        "Sustain the note at an even level while watching the loudness lane.",
        ("loudness",),
    ),
    ("dynamics.emphasis", "more stressed"): _g(
        "Over-stressed syllables",
        "You stress some syllables more than the singer {where}.",
        "Emphasis {diff} relative to the phrase (n={n}).",
        "Even out the stress pattern; speak the lyric with the reference's natural stress first.",
        "Speak the phrase in rhythm, matching which words the singer leans on.",
        ("loudness",),
    ),
    ("dynamics.emphasis", "less stressed"): _g(
        "Under-stressed syllables",
        "The singer leans on some syllables more than you {where}.",
        "Emphasis {diff} relative to the phrase (n={n}).",
        "Give the stressed words a little more weight.",
        "Speak the phrase in rhythm, matching which words the singer leans on.",
        ("loudness",),
    ),
    ("dynamics.attack", "punchier"): _g(
        "Attacks are punchier",
        "Your note starts are more sudden than the singer's {where}.",
        "Attack rise {diff} (n={n}).",
        "Soften the start of the note; begin with a gentle onset and let the tone bloom.",
        "Sing the entry at half volume, then add energy after the start.",
        ("loudness", "waveform"),
    ),
    ("dynamics.attack", "softer"): _g(
        "Attacks are softer",
        "The singer's note starts are more defined than yours {where}.",
        "Attack rise {diff} (n={n}).",
        "Give the start of the note a clearer, more decisive beginning.",
        "Sing the entry staccato a few times, then keep that clarity in the sustained version.",
        ("loudness", "waveform"),
    ),
    ("phonation.breathiness", "breathier"): _g(
        "Tone is breathier than the reference",
        "Your voice sounds airier than the singer's {where}.",
        "Breathiness index {user} vs {ref} (CPPS-based; median difference {diff}, n={n}).",
        "This likely means more air escapes between the vocal folds. Try a slightly firmer, cleaner onset and keep the airflow steady rather than blowing more air.",
        "On one comfortable pitch, alternate 3 s of airy tone with 3 s of clear tone, then match the reference's clarity on the problem note.",
        ("spectrogram", "pitch"),
        "inferred",
    ),
    ("phonation.breathiness", "clearer"): _g(
        "Reference tone is airier",
        "The singer lets more air into the sound {where}.",
        "Breathiness index {user} vs {ref} (CPPS-based; median difference {diff}, n={n}).",
        "Allow a little more air in the tone, like a gentle sigh, without letting the pitch sag.",
        "Sustain the note and add air gradually until it matches the reference's texture.",
        ("spectrogram", "pitch"),
        "inferred",
    ),
    ("phonation.h1h2", "lighter / more open"): _g(
        "Lighter source quality than the reference",
        "Your tone is lighter or airier at the source than the singer's {where}.",
        "H1-H2 {diff} on the same vowels (n={n}).",
        "A higher H1-H2 usually goes with a lighter, less firm vocal-fold closure. If you want the reference's weight, use a slightly firmer, speech-like onset.",
        "Say the lyric in a confident speaking voice, then sing it keeping that firmness.",
        ("spectrogram",),
        "inferred",
    ),
    ("phonation.h1h2", "heavier / more pressed"): _g(
        "Heavier / more pressed source quality",
        "Your tone sounds heavier or more squeezed than the singer's {where}.",
        "H1-H2 {diff} on the same vowels (n={n}).",
        "A lower H1-H2 usually goes with firmer vocal-fold closure. Release some effort: think of a lighter, easier sound.",
        "Sing the phrase on a gentle 'hoo' first, then on the lyric keeping the ease.",
        ("spectrogram",),
        "inferred",
    ),
    ("phonation.hnr", "noisier"): _g(
        "More noise in the tone",
        "Your tone has more noise (air or rasp) than the singer's {where}.",
        "HNR {user} vs {ref} (n={n}).",
        "Noise comes from air turbulence or irregular vibration; aim for a smoother, well-supported tone.",
        "Sustain the note softly and focus on a clean, steady sound.",
        ("spectrogram",),
        "inferred",
    ),
    ("phonation.hnr", "cleaner"): _g(
        "The reference has more texture",
        "The singer's tone has more noise or grit than yours {where}.",
        "HNR {user} vs {ref} (n={n}).",
        "This is a textural choice; add air or grit only if it serves the style.",
        "Listen in slow playback to identify the texture before imitating it.",
        ("spectrogram",),
        "inferred",
    ),
    ("articulation.consonant_duration", "longer"): _g(
        "Consonants held too long",
        "Some consonants last longer than the singer's {where}.",
        "Consonant duration {diff} (n={n}).",
        "Release the consonant sooner and move to the vowel; keep consonants crisp and short.",
        "Loop the word and speak it quickly in rhythm, then sing it keeping the consonant short.",
        ("phonetic", "spectrogram", "waveform"),
    ),
    ("articulation.consonant_duration", "shorter"): _g(
        "Consonants shorter than the reference",
        "The singer lingers on some consonants more than you {where}.",
        "Consonant duration {diff} (n={n}).",
        "Give these consonants more time, as the reference does.",
        "Loop the word and exaggerate the consonant length, then refine.",
        ("phonetic", "spectrogram", "waveform"),
    ),
    ("articulation.cv_ratio", "stronger"): _g(
        "Consonants are stronger",
        "Your consonants are louder relative to the vowels than the singer's {where}.",
        "Consonant-to-vowel level {diff} (n={n}).",
        "Soften these consonants; use less air pressure on them.",
        "Whisper the words, then sing with the same gentle consonants.",
        ("phonetic", "spectrogram"),
    ),
    ("articulation.cv_ratio", "softer"): _g(
        "Consonants are softer",
        "The singer articulates some consonants more strongly than you {where}.",
        "Consonant-to-vowel level {diff} (n={n}).",
        "Give these consonants a clearer, crisper release.",
        "Speak the lyric with exaggerated diction, then sing it keeping some of that clarity.",
        ("phonetic", "spectrogram"),
    ),
    ("articulation.missing_consonant", "missing"): _g(
        "Possibly dropped consonant",
        "A consonant the singer pronounces clearly may be missing {where}.",
        "Reference consonant not found at the aligned position (n={n}).",
        "Make sure this consonant is articulated; it may be too short or too quiet to register.",
        "Loop the word and speak it clearly, then sing it keeping the consonant.",
        ("phonetic", "spectrogram"),
    ),
    ("articulation.onset_type", "different"): _g(
        "Different vowel onset style",
        "You start some phrases differently (harder or breathier) than the singer {where}.",
        "Onset type: reference {ref}, take {user} (n={n}).",
        "Match the reference's onset: hard onsets start with a firm closure, breathy onsets let air flow first, balanced onsets start air and tone together.",
        "Sing the first vowel of the phrase on its own five times, matching the reference's start.",
        ("waveform", "loudness"),
    ),
    ("breath.presence", "missing breath"): _g(
        "Missing breath",
        "The singer breathes before {where}; you don't.",
        "Reference inhale present, none detected in the take (n={n}).",
        "Plan a breath at this point; it also helps you arrive at the phrase with the reference's energy.",
        "Loop the transition into the phrase and practise the quick inhale in rhythm.",
        ("breath", "waveform"),
    ),
    ("breath.presence", "extra breath"): _g(
        "Extra breath",
        "You breathe before {where} where the singer does not.",
        "Inhale detected in the take, none in the reference (n={n}).",
        "Connect the phrases without breathing here; plan your breath earlier.",
        "Sing the two phrases on one breath at a slower tempo, then speed up.",
        ("breath", "waveform"),
    ),
    ("breath.duration", "longer"): _g(
        "Longer inhales",
        "Your breaths take longer than the singer's {where}.",
        "Inhale duration {diff} (n={n}).",
        "Take quicker, lower breaths so they fit the phrase gap.",
        "Practise a silent half-second inhale in the gap before the phrase.",
        ("breath",),
    ),
    ("breath.duration", "shorter"): _g(
        "Shorter inhales",
        "The singer takes longer breaths than you {where}.",
        "Inhale duration {diff} (n={n}).",
        "Allow a slightly longer, relaxed inhale if you run short of air later.",
        "Loop the gap and breathe with the reference.",
        ("breath",),
    ),
    ("breath.level", "louder breath"): _g(
        "Audible inhales",
        "Your breaths are louder than the singer's {where}.",
        "Inhale level {diff} (n={n}).",
        "Open the throat and breathe through a relaxed mouth to make the inhale quieter.",
        "Practise silent inhales on a relaxed 'ah' shape.",
        ("breath",),
    ),
    ("breath.level", "quieter breath"): _g(
        "The reference breathes audibly",
        "The singer's breaths are more audible than yours {where}.",
        "Inhale level {diff} (n={n}).",
        "Audible breaths are a stylistic choice; copy them only if you want that intimacy.",
        "Listen to the breath in slow playback before imitating it.",
        ("breath",),
    ),
    ("breath.phrase_end", "airier endings"): _g(
        "Airier phrase endings",
        "Your phrase endings get airier than the singer's {where}.",
        "End-of-phrase CPPS change {user} vs {ref} (n={n}).",
        "Keep the tone clear until the release; plan the breath so you're not running out.",
        "Sing the last word of the phrase with full tone to the end.",
        ("spectrogram", "breath"),
        "inferred",
    ),
    ("breath.phrase_end", "clearer endings"): _g(
        "The reference lets air into endings",
        "The singer lets the tone go airy at phrase ends {where}.",
        "End-of-phrase CPPS change {user} vs {ref} (n={n}).",
        "Let the tone soften into air at the end of the phrase.",
        "Imitate the airy release on the last word slowly.",
        ("spectrogram", "breath"),
        "inferred",
    ),
    ("timbre.band_balance", "more energy in a band"): _g(
        "More energy in part of the spectrum",
        "Your tone has more energy around {band} than the singer's {where}.",
        "Largest band difference {diff} around {band} (level-normalised, n={n}).",
        "Part of this difference can come from your voice or microphone. If it's stylistic, vowel shape and resonance adjustments move it.",
        "Compare the spectrogram of both versions on a sustained vowel.",
        ("spectrogram",),
        "inferred",
    ),
    ("timbre.band_balance", "less energy in a band"): _g(
        "Less energy in part of the spectrum",
        "Your tone has less energy around {band} than the singer's {where}.",
        "Largest band difference {diff} around {band} (level-normalised, n={n}).",
        "Part of this difference can come from your voice or microphone. If it's stylistic, vowel shape and resonance adjustments move it.",
        "Compare the spectrogram of both versions on a sustained vowel.",
        ("spectrogram",),
        "inferred",
    ),
    ("timbre.centroid", "brighter"): _g(
        "Brighter tone",
        "Your tone is brighter than the singer's {where}.",
        "Spectral centroid {diff} (n={n}).",
        "A darker tone usually comes from a rounder vowel and more space in the mouth; try a slightly taller, rounder shape.",
        "Sing the phrase on a darker 'oo'-coloured version of each vowel, then relax toward the reference.",
        ("spectrogram",),
        "inferred",
    ),
    ("timbre.centroid", "darker"): _g(
        "Darker tone",
        "Your tone is darker than the singer's {where}.",
        "Spectral centroid {diff} (n={n}).",
        "A brighter tone usually comes from a more forward vowel and a slightly wider mouth shape.",
        "Sing the phrase on a brighter 'ee'-coloured version of each vowel, then relax toward the reference.",
        ("spectrogram",),
        "inferred",
    ),
    ("timbre.spr", "more ring"): _g(
        "More 2-4 kHz ring",
        "Your tone has more 'ring' than the singer's {where}.",
        "Singing power ratio {diff} (n={n}).",
        "If it sounds too edgy compared with the reference, soften the vowel and use a little less effort.",
        "Compare both on the spectrogram around 2-4 kHz while sustaining a vowel.",
        ("spectrogram",),
        "inferred",
    ),
    ("timbre.spr", "less ring"): _g(
        "Less 2-4 kHz ring",
        "The singer's tone has more 'ring' or projection than yours {where}.",
        "Singing power ratio {diff} (n={n}).",
        "More ring often comes from a slightly brighter, more focused vowel; a 'twangy' placement can add it.",
        "Sing the phrase on a bright 'nyah' first, then return to the lyric keeping some focus.",
        ("spectrogram",),
        "inferred",
    ),
}


GLOSSARY: dict[str, str] = {
    "cents": "A hundredth of a semitone. 100 cents = one piano key; differences below about 10-20 cents are hard to hear in context.",
    "F0": "Fundamental frequency: the rate at which the vocal folds vibrate, heard as pitch.",
    "formant": "A resonance of the vocal tract. F1 and F2 largely determine which vowel you hear; they depend on the shape of the mouth and throat and on the size of the vocal tract.",
    "F1": "First formant. Higher F1 usually means a more open vowel (lower jaw or tongue).",
    "F2": "Second formant. Higher F2 usually means a more front vowel (tongue further forward).",
    "normalisation": "Removing differences that come from anatomy, such as vocal-tract length, so that behaviour can be compared fairly.",
    "vibrato rate": "How many pitch oscillations per second (Hz). Typical classical and pop vibrato is 4.5-7 Hz.",
    "vibrato extent": "How far the pitch swings, reported as ± cents (half of peak-to-trough).",
    "HNR": "Harmonics-to-noise ratio: how much of the sound is periodic tone versus noise. Lower values sound airier or rougher.",
    "CPP": "Cepstral peak prominence: how clearly periodic the voice is. It is one of the most robust acoustic correlates of breathiness; CPPS is the smoothed version.",
    "H1-H2": "The level difference between the first two harmonics. Higher values usually go with lighter or breathier phonation, lower values with firmer or pressed phonation. It is affected by the vowel.",
    "jitter": "Cycle-to-cycle variation in the length of vocal-fold vibrations. Vibrato and fast pitch changes raise it, so it is shown but not scored.",
    "shimmer": "Cycle-to-cycle variation in amplitude.",
    "spectral centroid": "The 'centre of mass' of the spectrum; the strongest single correlate of perceived brightness.",
    "singing power ratio": "Energy of the strongest peak between 2 and 4 kHz relative to 0-2 kHz, associated with 'ring' or projection.",
    "LUFS": "Loudness units relative to full scale (ITU-R BS.1770), a standard perceptual loudness measure.",
    "DTW": "Dynamic time warping: an algorithm that finds which moment in your take corresponds to which moment in the reference, even when the tempo varies.",
    "confidence": "How much the measurement can be trusted, from 0 to 100%. It drops with noise, clipping, reverb, poor alignment or disagreement between estimators. Results below 25% are never scored.",
    "phonation": "How the vocal folds vibrate: breathy (air escapes), modal (balanced) or pressed (squeezed). Audio can only suggest this indirectly.",
    "register": "Vocal registers such as chest, falsetto or fry. Audio gives only indirect clues, so labels are experimental.",
    "scoop": "Starting a note below (or above) its pitch and sliding into it.",
    "portamento": "A deliberate glide between two notes.",
    "measured": "Read directly from the signal (for example pitch in Hz).",
    "derived": "Computed from measurements (for example a breathiness index).",
    "inferred": "An interpretation of measurements that is probably but not certainly true (for example 'the tongue is probably further forward').",
    "experimental": "A detector that works in many cases but has not been validated widely; treat as a hint.",
    "counterfactual": "An educational preview made by modifying your own recording in one respect. It is synthetic and is not a prediction of how you will sound.",
}


CATEGORY_HELP: dict[str, str] = {
    "pitch": "Note centres, attacks, scoops, releases and glides, compared note by note after removing any whole-key transposition.",
    "timing": "Phrase entries and rhythm within phrases, measured after removing your overall tempo and starting offset.",
    "vowel": "Vowel positions from formants, normalised for vocal-tract size so only articulation differences remain.",
    "vibrato": "Vibrato presence, rate, width and onset on sustained notes.",
    "dynamics": "Loudness shape and relative levels, independent of recording gain.",
    "phonation": "Breathiness and source quality (CPPS, HNR, H1-H2) on the same notes.",
    "articulation": "Consonant lengths, strength and vowel onset style.",
    "breath": "Where and how you breathe, and whether phrase endings get airy.",
    "timbre": "Level-independent spectral balance. Partly reflects anatomy and microphone, so it is weighted lightly.",
}
