from __future__ import annotations

from typing import Any

import soundfile as sf

from ..audio.errors import UserFacingError
from ..db import get_db
from ..storage import render_file
from ..store import misc as misc_store
from ..store import recordings as recording_store
from ..synthesis.counterfactual import (
    COUNTERFACTUAL_VERSION,
    TRANSFORMS,
    render_counterfactual,
    world_available,
)
from ..tasks.manager import TaskContext
from ..util import new_id, stable_hash
from .analysis_service import load_audio, load_view
from .comparison_service import get_alignment

SYNTHETIC_COMMENT = "SYNTHETIC counterfactual preview generated by Vibrato from the user's own recording. Not a real performance."


def available_transforms() -> list[dict[str, Any]]:
    out = []
    for key, info in TRANSFORMS.items():
        available = key != "breathiness" or world_available()
        out.append(
            {
                "id": key,
                **info,
                "available": available,
                "unavailable_reason": None
                if available
                else 'Requires the optional WORLD vocoder (pip install pyworld "setuptools<81").',
            }
        )
    return out


def render(take_id: str, transform: str, context: TaskContext | None = None) -> dict[str, Any]:
    with get_db().read() as conn:
        take = recording_store.get_recording(conn, take_id)
    if take is None or take["kind"] != "take":
        raise UserFacingError(
            "This take no longer exists.",
            "It may have been deleted.",
            "Refresh the project.",
            code="not_found",
        )
    reference_id = take.get("reference_recording_id")
    if not reference_id:
        raise UserFacingError(
            "This take has no reference.",
            "Counterfactual previews move your take toward a reference.",
            "Import a reference first.",
            code="no_reference",
        )
    if context:
        context.progress(0.05, "Loading analyses")
    ref_view, ref_analysis = load_view(reference_id)
    take_view, take_analysis = load_view(take_id)
    alignment, _ = get_alignment(
        reference_id, take_id, ref_view, take_view, take, ref_analysis, take_analysis
    )
    with get_db().read() as conn:
        reference = recording_store.get_recording(conn, reference_id)
    params_hash = stable_hash(
        {
            "transform": transform,
            "take": take["content_hash"],
            "ref": (reference or {}).get("content_hash"),
            "take_analysis": take_analysis["id"],
            "ref_analysis": ref_analysis["id"],
            "alignment": alignment.summary()["anchors"],
            "align_conf": round(alignment.overall_confidence, 3),
        }
    )
    with get_db().read() as conn:
        cached = misc_store.find_render(conn, take_id, reference_id, params_hash, COUNTERFACTUAL_VERSION)
    if cached and render_file(cached["id"]).exists():
        return cached
    if context:
        context.progress(0.3, f"Rendering {TRANSFORMS.get(transform, {}).get('label', transform)}")
    audio, sr = load_audio(take["content_hash"])
    result = render_counterfactual(transform, audio, sr, ref_view, take_view, alignment)
    render_id = new_id("cfr")
    path = render_file(render_id)
    path.parent.mkdir(parents=True, exist_ok=True)
    with sf.SoundFile(
        str(path), "w", samplerate=result.sample_rate, channels=1, subtype="PCM_16", format="WAV"
    ) as handle:
        handle.comment = SYNTHETIC_COMMENT
        handle.title = f"SYNTHETIC preview - {TRANSFORMS[transform]['label']}"
        handle.software = "Vibrato"
        handle.write(result.audio)
    description = {
        "label": TRANSFORMS[transform]["label"],
        "description": TRANSFORMS[transform]["description"],
        "method": TRANSFORMS[transform]["method"],
        "experimental": TRANSFORMS[transform]["experimental"],
        "output_timeline": result.output_timeline,
        "parameters": result.parameters,
        "disclaimer": "Educational preview made by modifying your own recording in one respect. It is synthetic and is not a prediction of how your voice would produce this.",
    }
    with get_db().tx() as conn:
        stored = misc_store.save_render(
            conn,
            render_id,
            take_id,
            reference_id,
            transform,
            {"transform": transform},
            params_hash,
            COUNTERFACTUAL_VERSION,
            str(path),
            result.approximate,
            result.warnings,
            description,
        )
    if context:
        context.progress(1.0, "Preview ready")
    return stored or {}
